title: BOVIFOCR
description: Biometria Ocular, Vivacidade de Imagens Faciais e Reconhecimento de Texto (OCR) em Documentos Oficiais
theme: just-the-docs

url: https://bovifocr.github.io

back_to_top: true
back_to_top_text: "Back to top"

color_scheme: "light"
