title: BOVIFOCR
description: Biometria Ocular, Vivacidade de Imagens Faciais e Reconhecimento de Texto (OCR) em Documentos Oficiais
theme: just-the-docs

url: https://bovifocr.github.io

aux_links:
  Template Repository: https://github.com/just-the-docs/just-the-docs-template
